export const ActionType = {

    SIGNUP_REQUEST: "[Auth] SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "[Auth] SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "[Auth] SIGNUP_FAILURE",

    LOGIN_REQUEST: "[Auth] LOGIN_REQUEST",
    LOGIN_SUCCESS: "[Auth] LOGIN_SUCCESS",
    LOGIN_FAILURE: "[Auth] LOGIN_FAILURE",

    FETCH_REQUEST_PRODUCT:"[ALL PRODUCT] FETCH_REQUEST_PRODUCT",    
    FETCH_SUCCESS_PRODUCT:"[ALL PRODUCT] FETCH_SUCCESS_PRODUCT",
    FETCH_FAILURE_PRODUCT:"[ALL PRODUCT] FETCH_FAILURE_PRODUCT",
    USER_NAME:"[PROFILE_NAME]USER_NAME"
};
